In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [2]:
ar1 = np.array([1, 2, 3, 4, 5])
print(ar1, type(ar1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
ar2 = np.array([[10, 20, 30], [40, 50, 60]])
print(ar2, type(ar2))

[[10 20 30]
 [40 50 60]] <class 'numpy.ndarray'>


In [4]:
ar3 = np.arange(1, 11, 2)
print(ar3, type(ar3))

[1 3 5 7 9] <class 'numpy.ndarray'>


In [5]:
ar4 = np.array([1, 2, 3, 4, 5, 6]).reshape(3,2)
print(ar4, type(ar4))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>


In [6]:
ar5 = np.zeros((2, 3))
print(ar5, type(ar5))

[[0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'>


In [7]:
ar6 = ar2[0:2, 0:2]
print(ar6, type(ar6))

[[10 20]
 [40 50]] <class 'numpy.ndarray'>


In [8]:
ar7 = ar2[0, :]
print(ar7, type(ar7))

[10 20 30] <class 'numpy.ndarray'>


In [9]:
ar8 = ar1 + 1
print(ar8, type(ar8))
print(ar1 + ar8)
print(ar8 - ar1)
print(ar1 * 2)
print(ar1 / 2)

[2 3 4 5 6] <class 'numpy.ndarray'>
[ 3  5  7  9 11]
[1 1 1 1 1]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [10]:
ar9 = np.dot(ar2, ar4)
print(ar9, type(ar9))

[[220 280]
 [490 640]] <class 'numpy.ndarray'>
