In [1]:
import torch
from numpy.distutils.system_info import wx_info

In [2]:
x = 3
w = torch.tensor(1.0, requires_grad=True)
z = w*x
out = z**2
out.backward()
print('out을 w로 미분한 값 :',w.grad)

out을 w로 미분한 값 : tensor(18.)


In [9]:
# tensor
import numpy as np
import torch

data = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x.size()
# x.shape
x.ndimension()
x.shape

torch.Size([3, 3])

In [10]:
x.reshape(-1, 3, 3)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [31]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x = torch.unsqueeze(x,1)
x.shape

torch.Size([3, 1, 3])

In [32]:
x = torch.squeeze(x)
x.shape

torch.Size([3, 3])

In [39]:
x.view(3, 3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [41]:
x.reshape(-1)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
x+np.array([1,1,1])

tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])

In [48]:
np.array([1,1,1]).shape

(3,)

In [56]:
w = torch.randn(5,3, dtype=torch.float)
x = torch.tensor([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
w.shape, x.shape

(torch.Size([5, 3]), torch.Size([3, 2]))

In [57]:
b = torch.randn(5,2,dtype=torch.float)
b.shape

torch.Size([5, 2])

In [65]:
w@x
wx = torch.mm(w,x)

In [67]:
z = wx+b
z

tensor([[ -3.9575,  -3.6300],
        [ -5.8461,  -7.7136],
        [ -4.5066,  -6.4298],
        [ -8.3117, -13.8973],
        [ -5.0045,  -4.0625]])

In [68]:
import numpy as np
import torch
from sklearn.datasets import make_blobs

In [71]:
n_dim=2
tr_x,tr_y=make_blobs(n_samples=80,n_features=2,centers=[[1,1],[-1,-1],[1,-1],[-1,1]],shuffle=True,cluster_std=0.3)
tt_x,tt_y=make_blobs(n_samples=20,n_features=2,centers=[[1,1],[-1,-1],[1,-1],[-1,1]],shuffle=True,cluster_std=0.3)

In [75]:
ck_y=tr_y.copy()
def label_map(y, from_, n):
    ck_y = y.copy()
    for i in from_:
        ck_y[y==i]=n
    return ck_y
tr_y=label_map(tr_y, [0,1], 0)
tr_y=label_map(tr_y, [2,3], 1)
tt_y=label_map(tt_y, [0,1], 0)
tt_y=label_map(tt_y, [2,3], 1)

array([0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1])